import { NextRequest, NextResponse } from "next/server";
import connectDB from "@/lib/db";
import SearchRequest from "@/models/SearchRequest";
import { GoogleGenAI } from "@google/genai";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { prompt } = body;

    if (!prompt || typeof prompt !== "string" || prompt.trim() === "") {
      return NextResponse.json(
        { success: false, error: "Prompt is required and must be a valid string." },
        { status: 400 }
      );
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { success: false, error: "GEMINI_API_KEY is not configured on the server." },
        { status: 500 }
      );
    }

    // Connect to MongoDB
    await connectDB();

    // Initialize the Gemini API client
    const ai = new GoogleGenAI({ apiKey });

    // Call the Gemini API with structured output configuration
const promptInstructions = `
You are an AI Corporate Event Concierge specializing in corporate offsites, leadership retreats, workshops, conferences, and executive meetings.

First determine whether the user's request is related to planning a corporate event, offsite, retreat, workshop, meeting, or business gathering.

If the request is NOT related to corporate event planning, return:

{
  "isValidRequest": false,
  "venueName": "Invalid Request",
  "location": "N/A",
  "estimatedCost": "N/A",
  "whyItFits": "Please provide details about the corporate event you would like to plan, including group size, duration, location, budget, or special requirements."
}

If the request IS related to corporate event planning:

1. Analyze the requirements.
2. Consider group size, budget, duration, and location preferences.
3. Recommend the SINGLE most suitable venue.
4. Estimate a realistic cost range.
5. Explain clearly why the venue is a good fit.

Return ONLY valid JSON matching the schema.

For valid corporate event requests return:
{
  "isValidRequest": true,
  "venueName": "...",
  "location": "...",
  "estimatedCost": "...",
  "whyItFits": "..."
}

User Request:
"${prompt}"

Do not return markdown.
Do not return any text outside the JSON response.
`;
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: promptInstructions,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: "OBJECT",
          properties: {
            venueName: {
              type: "STRING",
              description: "The name of the recommended venue or venue type (e.g., 'The Ritz-Carlton Tahoe')",
            },
           isValidRequest: {
                type: "BOOLEAN",
                 description: "Whether the user's request is related to corporate event planning and can be processed."
                   },
            location: {
              type: "STRING",
              description: "The city, state, or country of the venue (e.g., 'Lake Tahoe, California')",
             },
            estimatedCost: {
              type: "STRING",
              description: "Estimated cost range for the event in local currency (e.g., '₹2,50,000 - ₹3,00,000 total')"
            },
            whyItFits: {
              type: "STRING",
              description: "A professional 2-3 sentence justification explaining why this venue fits the group size, budget, retreat duration, and vibes requested.",
            },
          },
          required: ["venueName", "location", "estimatedCost", "whyItFits"],
        },
      },
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("No response content generated by Gemini.");
    }

    // Parse the structured output
    const proposalData = JSON.parse(responseText);

  if (proposalData.isValidRequest === false) {
  return NextResponse.json({
    success: false,
    message: proposalData.whyItFits,
    data: proposalData
  });
}

    // Save proposal to the database
    const newRequest = await SearchRequest.create({
      prompt,
      venueName: proposalData.venueName,
      location: proposalData.location,
      estimatedCost: proposalData.estimatedCost,
      whyItFits: proposalData.whyItFits,
    });

    return NextResponse.json({
      success: true,
      data: newRequest,
    });
  } catch (error: any) {
    console.error("Error in propose endpoint:", error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || "An error occurred while processing your request.",
      },
      { status: 500 }
    );
  }
}
